### ISSUE TITLE
earley-ocaml not available on opam with ocaml 4.08.0

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/ocaml-earley-ocaml#11]
15:03 ~/lambdapi opam install earley-ocaml
The following dependencies couldn't be met:
  - earley-ocaml → ocaml < 4.07.1
      base of this switch (use `--unlock-base' to force)

No solution found, exiting

**Comment by rlepigre** [comment]
We are aware of that, we just need to find the time to make the necessary changes. It is not completely trivial since the interface of OCaml's "compiler-libs" has changed a bit.

Since the "compiler-libs" are not marked as unstable anymore since 4.08.0, I guess we should base the implementation of the parser on the 4.08.0 version, and provide a compatibility package for previous versions of OCaml (implementing the same interface based on older versions of the library). Any thoughts on that @craff?

**Comment by craff** [comment]
On va passer à pacomb. :smile:

**Comment by rlepigre** [comment]
@fblanqui this repository is not the right one for `earley` (see the README).
